export const DEFAULT_ICONS: { name: string; url: string }[] = [
  { name: 'logo', url: 'assets/icons/logo.svg' },
  { name: 'menu', url: 'assets/icons/menu.svg' },
  { name: 'home', url: 'assets/icons/home.svg' },
  { name: 'shorts', url: 'assets/icons/shorts.svg' },
  { name: 'subscriptions', url: 'assets/icons/subscriptions.svg' },
  { name: 'library', url: 'assets/icons/library.svg' },
  { name: 'history', url: 'assets/icons/history.svg' },
  { name: 'account', url: 'assets/icons/account.svg' },
  { name: 'search', url: 'assets/icons/search.svg' },
  { name: 'more_vert', url: 'assets/icons/more_vert.svg' },
  { name: 'chevron_left', url: 'assets/icons/chevron_left.svg' },
  { name: 'chevron_right', url: 'assets/icons/chevron_right.svg' },
  { name: 'mic-fill', url: 'assets/icons/mic-fill.svg' },
  { name: 'fire', url: 'assets/icons/fire.svg' },
  { name: 'movies', url: 'assets/icons/movies.svg' },
  { name: 'game', url: 'assets/icons/game.svg' },
  { name: 'wireless', url: 'assets/icons/wireless.svg' },
  { name: 'champ_cup', url: 'assets/icons/champ_cup.svg' },
  { name: 'music_note', url: 'assets/icons/music_note.svg' },
  { name: 'settings', url: 'assets/icons/settings.svg' },
  { name: 'flag', url: 'assets/icons/flag.svg' },
  { name: 'help', url: 'assets/icons/help.svg' },
  { name: 'report', url: 'assets/icons/report.svg' },
  { name: 'yt_music', url: 'assets/icons/yt_music.svg' },
  { name: 'yt_kids', url: 'assets/icons/yt_kids.svg' },
  { name: 'yt_tv', url: 'assets/icons/yt_tv.svg' },
];
